--------------------------------------------------------
--  File created - Thursday-December-24-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HJ_AFFAIRINFORMATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_AFFAIRINFORMATION" 
   (	"AFFAIRINFORMATIONID" VARCHAR2(32 BYTE), 
	"INFORMATIONID" VARCHAR2(32 BYTE), 
	"HANDACCEPTOR" VARCHAR2(32 BYTE), 
	"MOVEWAY" VARCHAR2(500 BYTE), 
	"MOVEACCEPTOR" VARCHAR2(200 BYTE), 
	"MOVEACCEPTTEL" VARCHAR2(200 BYTE), 
	"MOVETIME" DATE, 
	"ANSWERMODE" VARCHAR2(1 BYTE), 
	"ANSWERTIME" DATE, 
	"ANSWERRESULT" VARCHAR2(1024 BYTE), 
	"CALLMODE" VARCHAR2(1 BYTE), 
	"CALLRESULT" VARCHAR2(1024 BYTE), 
	"HELPAPPROVE" VARCHAR2(1 BYTE), 
	"UNAPPROVECAUSE" VARCHAR2(2000 BYTE), 
	"REMARK" VARCHAR2(2000 BYTE), 
	"PRINCIPAL" VARCHAR2(32 BYTE), 
	"CALLER" VARCHAR2(32 BYTE), 
	"CALLTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_AFFAIRINFORMATION"."HANDACCEPTOR" IS '???????';
   COMMENT ON COLUMN "CCS"."HJ_AFFAIRINFORMATION"."ANSWERMODE" IS '????
1??
2??
3??
4????';
   COMMENT ON COLUMN "CCS"."HJ_AFFAIRINFORMATION"."CALLMODE" IS '??
1??
2??
3??
4????';
   COMMENT ON COLUMN "CCS"."HJ_AFFAIRINFORMATION"."HELPAPPROVE" IS '????
1??
2????
3???';
--------------------------------------------------------
--  DDL for Table HJ_AGENT
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_AGENT" 
   (	"USERID" VARCHAR2(32 BYTE), 
	"WORKNO" VARCHAR2(32 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"AGENTTYPE" VARCHAR2(20 BYTE), 
	"CARDTYPE" VARCHAR2(20 BYTE), 
	"MAINCCSIP" VARCHAR2(15 BYTE), 
	"BACKCCSIP" VARCHAR2(15 BYTE), 
	"TARGETDEVICE" VARCHAR2(20 BYTE), 
	"SERVERTYPE" VARCHAR2(20 BYTE), 
	"AUTOANSWER" VARCHAR2(1 BYTE), 
	"AUTORELEASE" VARCHAR2(1 BYTE), 
	"AUTORECONNECT" VARCHAR2(1 BYTE), 
	"HAVEBELL" VARCHAR2(1 BYTE), 
	"BELLTIME" VARCHAR2(3 BYTE), 
	"FREESTATUS" VARCHAR2(1 BYTE), 
	"MEDIAPLAY" VARCHAR2(1 BYTE), 
	"MEDIAFILENAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_AGENT"."USERID" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."WORKNO" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."PASSWORD" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."AGENTTYPE" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."CARDTYPE" IS 'APC???';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."MAINCCSIP" IS '?UIS??';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."BACKCCSIP" IS '?UIS??';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."TARGETDEVICE" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."SERVERTYPE" IS '?????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."AUTOANSWER" IS '???? 0:?????? 1:??????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."AUTORELEASE" IS '???? 0:???? 1:????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."AUTORECONNECT" IS '???? 0:?????? 1:????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."HAVEBELL" IS '???? 1:????? 0:?????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."BELLTIME" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."FREESTATUS" IS '??/???? 0:???????? 1:???????????,???????????';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."MEDIAPLAY" IS '?????.?????HaveBell?True????MediaPlay???????False?0:false 1:true ';
   COMMENT ON COLUMN "CCS"."HJ_AGENT"."MEDIAFILENAME" IS '?????? ??????????.';
--------------------------------------------------------
--  DDL for Table HJ_AREA
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_AREA" 
   (	"AREAID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_AREA"."AREAID" IS '??ID(uuid)';
   COMMENT ON COLUMN "CCS"."HJ_AREA"."NAME" IS '??';
--------------------------------------------------------
--  DDL for Table HJ_AREA_SUB
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_AREA_SUB" 
   (	"AREASUBID" VARCHAR2(32 BYTE), 
	"AREAID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_AREA_SUB"."AREAID" IS '-1    ??
01    ??
0101  ??

???';
--------------------------------------------------------
--  DDL for Table HJ_BLACKLIST
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_BLACKLIST" 
   (	"PHONE_ID" VARCHAR2(32 BYTE), 
	"PHONE_NUM" VARCHAR2(100 BYTE), 
	"LEVELS" VARCHAR2(2 BYTE), 
	"REMARK" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_CLASSOFENTPRISE
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_CLASSOFENTPRISE" 
   (	"ENTPRISEID" VARCHAR2(32 BYTE), 
	"ENTCLASSID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_CLASSOFENTPRISE"."ENTCLASSID" IS '-1    ??
01    ??
0101  ??
010101??';
--------------------------------------------------------
--  DDL for Table HJ_DICT
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_DICT" 
   (	"DICTID" NVARCHAR2(32), 
	"DICTTYPE" NVARCHAR2(100), 
	"SORTINDEX" NVARCHAR2(255), 
	"VAL" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_ENTCLASS
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_ENTCLASS" 
   (	"ENTCLASSID" VARCHAR2(32 BYTE), 
	"ENTCLASSNAME" VARCHAR2(250 BYTE), 
	"PARENTENTCLASSID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_ENTCLASS"."ENTCLASSID" IS '-1    ??
01    ??
0101  ??
010101??';
--------------------------------------------------------
--  DDL for Table HJ_ENTPRISE
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_ENTPRISE" 
   (	"ENTPRISEID" VARCHAR2(32 BYTE), 
	"ENTPRISENAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"LAWDEPUTY" VARCHAR2(100 BYTE), 
	"REGMONEY" VARCHAR2(100 BYTE), 
	"SERVICETIME" VARCHAR2(100 BYTE), 
	"LINKTEL" VARCHAR2(1024 BYTE), 
	"SERVICETEL" VARCHAR2(1024 BYTE), 
	"MEMBERSIGN" VARCHAR2(1 BYTE), 
	"REGISTERCODE" VARCHAR2(50 BYTE), 
	"TAXCODE" VARCHAR2(50 BYTE), 
	"DEALRANGE" VARCHAR2(1024 BYTE), 
	"LINKNAME" VARCHAR2(100 BYTE), 
	"ENTPRISENO" VARCHAR2(20 BYTE), 
	"SERVICESTYPE" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT '1'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_ENTPRISE"."MEMBERSIGN" IS '???
Y: ? N: ?';
   COMMENT ON COLUMN "CCS"."HJ_ENTPRISE"."SERVICESTYPE" IS 'Y: ??? N: ????';
   COMMENT ON COLUMN "CCS"."HJ_ENTPRISE"."STATUS" IS 'Y: ??? N:????';
--------------------------------------------------------
--  DDL for Table HJ_INFORMATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_INFORMATION" 
   (	"INFORMATIONID" VARCHAR2(32 BYTE), 
	"HELPNAME" VARCHAR2(20 BYTE), 
	"HELPMODE" VARCHAR2(1 BYTE), 
	"HELPTEL" VARCHAR2(50 BYTE), 
	"HELPADDR" VARCHAR2(50 BYTE), 
	"HELPCONTENT" VARCHAR2(1024 BYTE), 
	"HELPTYPE" VARCHAR2(1 BYTE), 
	"HELPAREA" VARCHAR2(10 BYTE), 
	"CREATOR" VARCHAR2(32 BYTE), 
	"CREATETIME" DATE, 
	"HELPGROUP" VARCHAR2(1 BYTE), 
	"FINISHTIME" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"CANCELER" VARCHAR2(32 BYTE), 
	"CANCELTIME" DATE, 
	"DELIVERER" VARCHAR2(32 BYTE), 
	"DELIVERMODE" VARCHAR2(1 BYTE), 
	"DELIVERTIME" DATE, 
	"AFFAIEACCEPTOR" VARCHAR2(32 BYTE), 
	"RECORDFILENAME" VARCHAR2(200 BYTE), 
	"ISRECORD" VARCHAR2(1 BYTE), 
	"CALLID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 276824064 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."HELPMODE" IS '????
1??
2??
3??';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."HELPTYPE" IS '???
1?????
2?????
2?????';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."HELPAREA" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."HELPGROUP" IS '????: ??,??,????';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."STATUS" IS '???
1???,?????
2?????????????????
3????
4????';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."DELIVERMODE" IS '????
1??
2??
3??
4????';
   COMMENT ON COLUMN "CCS"."HJ_INFORMATION"."ISRECORD" IS 'Y: RECORD N: NO RECORD';
--------------------------------------------------------
--  DDL for Table HJ_LIFEINFORMATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_LIFEINFORMATION" 
   (	"LIFEINFORMATIONID" VARCHAR2(32 BYTE), 
	"INFORMATIONID" VARCHAR2(32 BYTE), 
	"RECEIVERTYPE" VARCHAR2(1 BYTE), 
	"RECEIVERID" VARCHAR2(32 BYTE), 
	"CALLMODE" VARCHAR2(1 BYTE), 
	"CALLRESULT" VARCHAR2(1024 BYTE), 
	"HELPAPPROVE" VARCHAR2(1 BYTE), 
	"UNAPPROVECAUSE" VARCHAR2(1024 BYTE), 
	"REMARK" VARCHAR2(1024 BYTE), 
	"DEALRESULT" VARCHAR2(1 BYTE), 
	"DEALCONTENT" VARCHAR2(1024 BYTE), 
	"PRINCIPAL" VARCHAR2(32 BYTE), 
	"CALLER" VARCHAR2(32 BYTE), 
	"CALLTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 83886080 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_LIFEINFORMATION"."RECEIVERTYPE" IS '??
1???
2????';
   COMMENT ON COLUMN "CCS"."HJ_LIFEINFORMATION"."RECEIVERID" IS '??????1??????
           2???????';
   COMMENT ON COLUMN "CCS"."HJ_LIFEINFORMATION"."CALLMODE" IS '????
1??
2??
3??
4????';
   COMMENT ON COLUMN "CCS"."HJ_LIFEINFORMATION"."HELPAPPROVE" IS '????
1??
2????
3???';
   COMMENT ON COLUMN "CCS"."HJ_LIFEINFORMATION"."DEALRESULT" IS '????
1??
2????
3???';
--------------------------------------------------------
--  DDL for Table HJ_LONELYHELP
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_LONELYHELP" 
   (	"HELPID" VARCHAR2(32 BYTE), 
	"LONELYMANID" VARCHAR2(32 BYTE), 
	"HELPCONTENT" VARCHAR2(1024 BYTE), 
	"CREATOR" VARCHAR2(32 BYTE), 
	"CREATETIME" DATE, 
	"FINISHTIME" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"DELIVERER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."HELPID" IS 'ID';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."LONELYMANID" IS '???ID';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."HELPCONTENT" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."CREATOR" IS '???';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."CREATETIME" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."FINISHTIME" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."STATUS" IS '?? P????? E???';
   COMMENT ON COLUMN "CCS"."HJ_LONELYHELP"."DELIVERER" IS '????:?????ID';
--------------------------------------------------------
--  DDL for Table HJ_LONELYMANINFO
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_LONELYMANINFO" 
   (	"MANID" VARCHAR2(32 BYTE), 
	"MANNAME" VARCHAR2(40 BYTE), 
	"MANSEX" VARCHAR2(20 BYTE), 
	"BIRTHDAY" VARCHAR2(50 BYTE), 
	"IDCARDNO" VARCHAR2(100 BYTE), 
	"AREA" VARCHAR2(1000 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"TELPHONE" VARCHAR2(200 BYTE), 
	"FAMILYTYPE" VARCHAR2(1 BYTE), 
	"FAMILYINFO" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."MANNAME" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."MANSEX" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."BIRTHDAY" IS '?????2015/04/30';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."IDCARDNO" IS '?????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."AREA" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."ADDRESS" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."TELPHONE" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."FAMILYTYPE" IS 'L:????????D???????';
   COMMENT ON COLUMN "CCS"."HJ_LONELYMANINFO"."FAMILYINFO" IS '??????';
--------------------------------------------------------
--  DDL for Table HJ_MESSAGE
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_MESSAGE" 
   (	"MESSAGEID" VARCHAR2(32 BYTE), 
	"MESSAGETYPE" VARCHAR2(4 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1024 BYTE), 
	"CREATEDATE" DATE, 
	"CREATOR" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_MESSAGE"."MESSAGETYPE" IS '????';
--------------------------------------------------------
--  DDL for Table HJ_OPERATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_OPERATION" 
   (	"OPERATIONID" VARCHAR2(32 BYTE), 
	"OPERATIONNAME" VARCHAR2(250 BYTE), 
	"CLASSNAME" VARCHAR2(250 BYTE), 
	"ACTION" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_PARTYMEMBERFORLONELY
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_PARTYMEMBERFORLONELY" 
   (	"MEMBERID" VARCHAR2(32 BYTE), 
	"MEMBERNAME" VARCHAR2(20 BYTE), 
	"MEMBERSEX" VARCHAR2(1 BYTE), 
	"BIRTHDAY" VARCHAR2(10 BYTE), 
	"WORKDEPT" VARCHAR2(200 BYTE), 
	"LINKPHONE" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(1000 BYTE), 
	"SPECIALTY" VARCHAR2(1000 BYTE), 
	"LONELYMANID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 196608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."MEMBERID" IS 'ID';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."MEMBERNAME" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."MEMBERSEX" IS '???M??? W???';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."BIRTHDAY" IS '?????2015/04/30';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."WORKDEPT" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."LINKPHONE" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."ADDRESS" IS '????';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."SPECIALTY" IS '??';
   COMMENT ON COLUMN "CCS"."HJ_PARTYMEMBERFORLONELY"."LONELYMANID" IS '??????';
--------------------------------------------------------
--  DDL for Table HJ_POWERSTAFF
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_POWERSTAFF" 
   (	"PID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(1024 BYTE), 
	"PHONE" VARCHAR2(1024 BYTE), 
	"CATEGORY" VARCHAR2(1 BYTE), 
	"REMARK" VARCHAR2(1024 BYTE), 
	"DELETEFLAG" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CREATETIME" TIMESTAMP (6), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF"."CATEGORY" IS '1:负责人 2:安全负责人 3:全镇机动 4:普通电工';
   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF"."DELETEFLAG" IS 'Deleted:1 or 0';
   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF"."UPDATEDT" IS '更新时间';
   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF"."LASTHANDLER" IS '最后修改人';
--------------------------------------------------------
--  DDL for Table HJ_POWERSTAFF_AREA
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_POWERSTAFF_AREA" 
   (	"PID" VARCHAR2(32 BYTE), 
	"STAFFID" VARCHAR2(32 BYTE), 
	"AREASUBID" VARCHAR2(32 BYTE), 
	"DELETEFLAG" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CREATETIME" TIMESTAMP (6), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF_AREA"."DELETEFLAG" IS 'Deleted:1 or 0';
   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF_AREA"."UPDATEDT" IS '更新时间';
   COMMENT ON COLUMN "CCS"."HJ_POWERSTAFF_AREA"."LASTHANDLER" IS '最后修改人';
--------------------------------------------------------
--  DDL for Table HJ_REFER
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_REFER" 
   (	"REFERID" VARCHAR2(32 BYTE), 
	"REFERTYPE" VARCHAR2(4 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"LASTUPDATOR" VARCHAR2(200 BYTE), 
	"LASTUPDATEDT" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 458752 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_REFER"."REFERTYPE" IS '?????
RXDH:????
RCXX:????
YWZX:????';
--------------------------------------------------------
--  DDL for Table HJ_REFERINFORMATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_REFERINFORMATION" 
   (	"REFERINFORMATIONID" VARCHAR2(32 BYTE), 
	"INFORMATIONID" VARCHAR2(32 BYTE), 
	"RESULT" VARCHAR2(1024 BYTE), 
	"DEALER" VARCHAR2(32 BYTE), 
	"DEALTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 72351744 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_ROLE
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_ROLE" 
   (	"ROLEID" VARCHAR2(32 BYTE), 
	"ROLENAME" VARCHAR2(254 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_ROLEOPERATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_ROLEOPERATION" 
   (	"ROLEID" VARCHAR2(32 BYTE), 
	"OPERATIONID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_SMSRECV
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_SMSRECV" 
   (	"SMSID" VARCHAR2(32 BYTE), 
	"TELNUM" VARCHAR2(32 BYTE), 
	"CONTENT" VARCHAR2(2048 BYTE), 
	"RECVDT" DATE, 
	"STATUS" VARCHAR2(1 BYTE), 
	"UPDATEDT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_SMSRECV"."STATUS" IS 'N: NEW
C: COMPLETE -- HAVE IMPORT TO 96345';
--------------------------------------------------------
--  DDL for Table HJ_USER
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_USER" 
   (	"USERID" VARCHAR2(32 BYTE), 
	"LOGINNAME" VARCHAR2(20 BYTE), 
	"LOGINPASSWORD" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"HOMETEL" VARCHAR2(20 BYTE), 
	"HOMEADDR" VARCHAR2(50 BYTE), 
	"HOMEPOSTCODE" VARCHAR2(10 BYTE), 
	"OFFICETEL" VARCHAR2(20 BYTE), 
	"OFFICEADDR" VARCHAR2(50 BYTE), 
	"OFFICEPOSTCODE" VARCHAR2(10 BYTE), 
	"LINKMOBILE" VARCHAR2(20 BYTE), 
	"EMAILADDR" VARCHAR2(50 BYTE), 
	"ONJOB" VARCHAR2(1 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_USERROLE
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_USERROLE" 
   (	"USERID" VARCHAR2(32 BYTE), 
	"ROLEID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  DDL for Table HJ_VOLUNTEER
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_VOLUNTEER" 
   (	"VOLUNTEERID" VARCHAR2(32 BYTE), 
	"VOLUNTEERNAME" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(1 BYTE), 
	"SERVICENAME" VARCHAR2(200 BYTE), 
	"SERVICETIME" VARCHAR2(50 BYTE), 
	"REMARK" VARCHAR2(200 BYTE), 
	"LINKTEL" VARCHAR2(1024 BYTE), 
	"LINKMOBILE" VARCHAR2(1024 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"AREAID" VARCHAR2(32 BYTE), 
	"AREASUBID" VARCHAR2(32 BYTE), 
	"VOLUNTEERNO" VARCHAR2(20 BYTE), 
	"SERVICETYPE" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_VOLUNTEER"."SEX" IS '??
1?
2?';
   COMMENT ON COLUMN "CCS"."HJ_VOLUNTEER"."SERVICETIME" IS '???
1???
2?24??';
   COMMENT ON COLUMN "CCS"."HJ_VOLUNTEER"."SERVICETYPE" IS 'Y????
N?????';
   COMMENT ON COLUMN "CCS"."HJ_VOLUNTEER"."STATUS" IS '??:0:???? 1:???';
