--------------------------------------------------------
--  File created - Sunday-December-27-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HJ_POWERINFORMATION
--------------------------------------------------------

  CREATE TABLE "CCS"."HJ_POWERINFORMATION" 
   (	"PID" VARCHAR2(32 BYTE), 
	"INFORMATIONID" VARCHAR2(32 BYTE), 
	"POWERSTAFFID" VARCHAR2(20 BYTE), 
	"REMARK" VARCHAR2(1024 BYTE), 
	"DELETEFLAG" VARCHAR2(1 BYTE) DEFAULT 0, 
	"CREATETIME" TIMESTAMP (6), 
	"UPDATEDT" TIMESTAMP (6), 
	"LASTHANDLER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;

   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."INFORMATIONID" IS '接单信息主id';
   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."POWERSTAFFID" IS '电工ID';
   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."DELETEFLAG" IS '0:在用;1：已删除';
   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."CREATETIME" IS '创建时间';
   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."UPDATEDT" IS '修改时间';
   COMMENT ON COLUMN "CCS"."HJ_POWERINFORMATION"."LASTHANDLER" IS '最后修改人';
--------------------------------------------------------
--  DDL for Index HJ_POWER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CCS"."HJ_POWER_PK" ON "CCS"."HJ_POWERINFORMATION" ("PID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS" ;
--------------------------------------------------------
--  Constraints for Table HJ_POWERINFORMATION
--------------------------------------------------------

  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("LASTHANDLER" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("UPDATEDT" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("CREATETIME" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("DELETEFLAG" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" ADD CONSTRAINT "HJ_POWER_PK" PRIMARY KEY ("PID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CCS"  ENABLE;
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("POWERSTAFFID" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("INFORMATIONID" NOT NULL ENABLE);
  ALTER TABLE "CCS"."HJ_POWERINFORMATION" MODIFY ("PID" NOT NULL ENABLE);
